DROP DATABASE IF EXISTS INCIDENCIAS;
CREATE DATABASE INCIDENCIAS;
USE INCIDENCIAS;
CREATE TABLE INCIDENCIA (
	CODIGO INTEGER,
    ESTADO VARCHAR (100) NOT NULL,
    PUESTO VARCHAR (15),
    PROBLEMA VARCHAR(255),
    RESOLUCION VARCHAR(255),
    CONSTRAINT PK_CODIGO PRIMARY KEY(CODIGO)
);